version: "3"
services:
  backend:
    container_name: backend
    build: .
    image: backend
    environment:
      - MYSQL_DATABASE=cfandb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=kamin124712
    volumes:
      - ~/backend_data:/public/product-img
    networks:
      allnetwork:
        ipv4_address: 172.20.0.3
    # ports:
    #   - "3000:3000"

networks:
  default:
    external:
      name: allnetwork
  allnetwork:
    external: true
