server:
  port: 3000

spring:
  sql: 
    init: 
      platform: mysql
      mode: always

  jpa:
    database-platform=org:
      hibernate:
        dialect: MySQL5InnoDBDialect
        use-new-id-generator-mappings: false

  servlet: 
    multipart: 
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  profiles:
    active: dev