server:
  port: 3000

spring:
  datasource: 
    url: jdbc:mysql:http://13.76.27.34:3306/cfandb
    username: root
    password: kamin124712

  sql: 
    init: 
      platform: mysql
      mode: always
  jpa:
    database-platform=org:
      hibernate:
        dialect: MySQL5InnoDBDialect
        use-new-id-generator-mappings: false
  servlet: 
    multipart: 
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

cfan:
  email:
    from: cfanint222test@gmail.com
  token:
    secret: secretfordev 
    issuer: cfanBackend
  storage: 
    location: ./public/img
  origin: 
    host: http://localhost:8080,http://13.76.27.34:8080,http://13.76.27.34
    method: GET,POST,PUT,HEAD,DELETE,PATCH,OPTIONS
  profiles:
    active: dev
