spring:
  datasource:
    url: jdbc:mysql://172.20.0.4:3306/cfandb
    username: root
    password: kamin124712

  mail:
    host: smtp.gmail.com
    port: 587
    username: cfanint222test
    password: rotmpdzovxpdwiom
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cfan:
  email:
    from: cfanint222test@gmail.com
  token:
    secret: secretfordev
    issuer: cfanBackend
  storage:
    location: ./public/img
  origin:
    host: https://cfan.ddns.net/
    method: GET,POST,PUT,HEAD,DELETE,PATCH,OPTIONS
    header: Content-Type,Option,Authorization
